import {useEffect,useState,type FormEvent} from 'react';
import {getPaymentPlan,createStudioPayment,getStudioPayment,type PaymentPlan} from '../lib/api';
export function DownloadUpgrade({jobId}:{jobId:string}){
 const [plan,setPlan]=useState<PaymentPlan|null>(null),[payment,setPayment]=useState<{id:string;status:string}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;void getPaymentPlan().then(p=>{if(active)setPlan(p)}).catch(()=>{if(active)setPlan({available:false})});return()=>{active=false}},[]);
 useEffect(()=>{if(!payment||!['created','pending','unknown'].includes(payment.status))return;let active=true;const timer=setInterval(()=>{void getStudioPayment(payment.id).then(p=>{if(active){setPayment({id:payment.id,status:p.status});setError('')}}).catch(()=>{if(active)setError('Payment status is temporarily unavailable. Do not pay again.');})},3000);return()=>{active=false;clearInterval(timer)}},[payment?.id,payment?.status]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||payment)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const p=await createStudioPayment({jobId,method:'mobile',phone:String(f.get('phone')),firstname:String(f.get('firstname')),lastname:String(f.get('lastname'))});setPayment(p);sessionStorage.setItem(`studio-payment-${jobId}`,p.id);}catch(err){setError(err instanceof Error?err.message:'Payment unavailable.')}finally{setBusy(false)}}
 useEffect(()=>{const saved=sessionStorage.getItem(`studio-payment-${jobId}`);if(saved)setPayment({id:saved,status:'pending'})},[jobId]);
 return <div className="mt-5 space-y-4 border-t border-border pt-5"><h3 className="font-semibold">Need more downloads?</h3>
 {!plan?<p role="status">Checking upgrade availability…</p>:!plan.available?<><p className="text-sm text-foreground-muted">Paid upgrades are not available yet. Your free allowance resets at midnight UTC.</p><button disabled className="min-h-touch rounded-md border border-border px-4 opacity-60">Upgrade unavailable</button></>:payment?<div role="status" className="rounded-lg border border-border bg-background p-4">
 {payment.status==='completed'?<><h4 className="font-semibold">Payment confirmed</h4><p>Your download allowance has been updated. Use Download video above to continue.</p></>:['failed','voided','expired'].includes(payment.status)?<><h4 className="font-semibold">Payment {payment.status==='voided'?'cancelled':payment.status}</h4><p>No download entitlement was granted for this payment.</p></>:<><h4 className="font-semibold">Payment pending</h4><p>{payment.status==='unknown'?'We are checking whether your payment was initiated. Do not pay again.':'Complete the payment on your phone. Waiting for verified provider confirmation.'}</p></>}
 </div>:<form onSubmit={submit} className="space-y-3"><p>{plan.name}: {plan.amount?.toLocaleString()} TZS · {plan.downloads} downloads/day · {Math.round((plan.duration??0)/3600)} hours</p>{[['firstname','First name'],['lastname','Last name'],['phone','Mobile money number (255…)']].map(([name,label])=><label key={name} className="block text-sm">{label}<input required name={name} maxLength={name==='phone'?12:80} pattern={name==='phone'?'255[67][0-9]{8}':undefined} className="mt-1 block w-full rounded-md border border-border bg-background p-3" /></label>)}<button disabled={busy||!plan.methods?.includes('mobile')} className="min-h-touch rounded-md bg-gradient-primary px-5 disabled:opacity-50">{busy?'Starting payment…':'Pay with mobile money'}</button></form>}
 {error&&<p role="alert" className="text-sm text-danger">{error}</p>}
 </div>;
}
