import test from 'node:test';import assert from 'node:assert/strict';import {createHmac,randomUUID} from 'node:crypto';
import {PAID_PLANS,findPlan,checkoutEnabled,providerBase,PAYMENT_BASE,validSignature,parseEvent,paymentBody,createPayment} from './snippe.js';
const secret='synthetic-test-secret',ts=String(Math.floor(Date.now()/1000));
const payload={id:'evt_fixture',api_version:'2026-01-25',type:'payment.completed',data:{reference:'pi_fixture',status:'completed',amount:{value:1500,currency:'TZS'},metadata:{product:'hasheemstudio',studio_payment_intent:randomUUID()}}};
const raw=Buffer.from(JSON.stringify(payload)),sig=createHmac('sha256',secret).update(ts+'.').update(raw).digest('hex');
test('raw signature, stale/future time, malformed/invalid signature',()=>{assert(validSignature(raw,ts,sig,secret));assert(!validSignature(Buffer.from('{}'),ts,sig,secret));assert(!validSignature(raw,ts,sig,secret,Date.now()+301000));assert(!validSignature(raw,ts,sig,secret,Date.now()-301000));for(const v of ['',sig+'x',[],null])assert(!validSignature(raw,ts,v,secret));});
test('strict provider shape, version, amount and Studio correlation',()=>{assert(parseEvent(raw));for(const change of [{api_version:'old'},{type:'payout.completed'},{data:{...payload.data,amount:1500}},{data:{...payload.data,metadata:{order_id:randomUUID()}}},{data:{...payload.data,status:'failed'}}])assert.equal(parseEvent(Buffer.from(JSON.stringify({...payload,...change}))),null);assert.equal(parseEvent(Buffer.from('{')),null);});
test('no credential or approval means no checkout',()=>{assert.equal(checkoutEnabled({}),false);assert.equal(checkoutEnabled({STUDIO_CHECKOUT_ENABLED:'true'}),false);assert.equal(checkoutEnabled({STUDIO_CHECKOUT_ENABLED:'true',STUDIO_PAYMENT_APPROVED:'true',SNIPPE_API_KEY:'snp_x',SNIPPE_WEBHOOK_SECRET:'s'}),true);assert.equal(checkoutEnabled({STUDIO_CHECKOUT_ENABLED:'true',STUDIO_PAYMENT_APPROVED:'true',SNIPPE_API_KEY:'bad',SNIPPE_WEBHOOK_SECRET:'s'}),false);});
test('approved plan terms are fixed server-side and unknown codes are rejected',()=>{assert.deepEqual([PAID_PLANS.weekly.amount,PAID_PLANS.weekly.videos,PAID_PLANS.weekly.days],[5000,20,7]);assert.deepEqual([PAID_PLANS.monthly.amount,PAID_PLANS.monthly.videos,PAID_PLANS.monthly.days],[19900,50,30]);for(const bad of ['free','__proto__','constructor',undefined,7,'Weekly'])assert.equal(findPlan(bad),null);assert.equal(findPlan('weekly')?.amount,5000);assert.equal(findPlan('monthly')?.amount,19900);});
test('request contract and redirects are server-owned',()=>{const body=paymentBody({id:randomUUID(),amount:1500,method:'mobile',phone:'255700000000',customer:{firstname:'Test',lastname:'Fixture',email:'fixture@example.invalid'}},'https://api.hasheemstudio.com/webhooks/snippe');assert.equal(body.details.amount,1500);assert.equal(body.details.currency,'TZS');assert.equal(body.payment_type,'mobile');assert.equal(body.phone_number,'255700000000');assert.equal(body.metadata.product,'hasheemstudio');assert.throws(()=>paymentBody({id:randomUUID(),jobId:randomUUID(),amount:1500,method:'mobile',phone:'255700000000',customer:{}},'https://evil.invalid/webhooks/snippe'));});
test('reject malformed keys and oversized idempotency before network',async()=>{await assert.rejects(createPayment({} as never,'bad','a'.repeat(30)));await assert.rejects(createPayment({} as never,'snp_fixture','a'.repeat(31)));});

test('provider origin cannot be redirected in production-like configs',()=>{assert.equal(providerBase({}),PAYMENT_BASE);assert.equal(providerBase({SNIPPE_API_BASE:'https://evil.example'} as never),PAYMENT_BASE);assert.equal(providerBase({SNIPPE_API_BASE:'http://10.0.0.5:9'} as never),PAYMENT_BASE);assert.equal(providerBase({SNIPPE_API_BASE:'http://127.0.0.1:9999'} as never),'http://127.0.0.1:9999');});
